services:
  SwooleBundle\Command\ServerCommand:
    public: true
    arguments: [ '@service_container' ]
    tags: [ 'console.command' ]
  SwooleBundle\EventListener\SwooleServerListener:
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: swoole.server.request }
  SwooleBundle\EventListener\KernelListener:
    arguments: [ '@service_container' ]
    tags:
      - { name: kernel.event_listener, event: kernel.request }
      - { name: kernel.event_listener, event: kernel.response }